#spring.datasource.url=jdbc:mysql://localhost:3306/mydb
#spring.datasource.username=Aommy
#spring.datasource.password=Aommy07092541
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sme?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: Aommy
    password: Aommy07092541
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
  mail:    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
server:
  port: 7070
